Newspaper/Newspaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('account/', include('allauth.urls')),

]

Newspaper/news/urls.py
from django.urls import path
from .views import PostList, PostDetailView, Search, PostCreateView
from .views import PostDeleteView, PostUpdateView, subscribe_me
                # импортируем наши представления

# namespace = 'news'
urlpatterns = [
    # path — означает путь. В данном случае путь ко всем товарам у нас останется пустым,
    # позже станет ясно почему
    path('', PostList.as_view()),
    # т.к. сам по себе это класс, то нам надо представить этот класс в виде view. Для этого
    # вызываем метод as_view
    path('<int:pk>', PostDetailView.as_view(), name='post'),
    # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
    path('search/', Search.as_view()),
    path('create/', PostCreateView.as_view(), name='post_create'), # Ссылка на создание товара
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('<int:pk>/subscribe/', subscribe_me, name='subscribe'),
]

Newspaper/templates/base.html
from django.contrib import admin

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block head_title %}{% endblock head_title %}</title>
    </head>
    <body>
        {% block body %}
          {% block content %}
          {% endblock content %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </body>
</html>

Newspaper/templates/post.html
{% extends 'flatpages/default.html' %}

{% block title %}
  {{ post.post_name }}
{% endblock title %}

{% block content %}
  <table>
      <thead>
          <th>
              Название
          </th>
          <th>
              Дата публикации
          </th>
          <th>
              Содержание
          </th>
      </thead>
      <tr>
          <td>
              {{ post.post_name }}
          </td>
          <td>
              {{ post.post_date | date:'d M Y' }}
          </td>
          <td>
              {{ post.content }}
          </td>
      </tr>
  </table>
<hr>
  {% if is_not_subscribe %}
    <button> <a href="{% url 'news:subscribe' post.id %}">Подписаться</a> </button>
  {% endif %}
{% endblock content %}

Newspaper/templates/post_create.html
{% extends 'flatpages/default.html' %}

{% block title %} Создание записи {% endblock title %}
 
{% block content %}
    <h3>Информация о новой записи</h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }} <!-- Теперь нам нужна только готовая форма и кнопка -->
        <input type="submit" value="Сохранить запись">
    </form>
{% endblock content %}

Newspaper/templates/post_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ post.post_name }}</title>
</head>
<body>
    <p>Здравствуй, {{ user.username }}. Новая статья в твоём любимом разделе!</p>
    <hr>
    <h2>{{ post.post_name }}</h2>
    <p> {{ post.content|truncatechars:50 }} </p>
</body>
</html>

Newspaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block title %}
  {{ post.post_name }}
{% endblock title %}

{% block content %}
  <h2>Вы действительно хотите удалить данную запись?</h2>
  <table>
      <thead>
          <th>
              Название
          </th>
          <th>
              Дата публикации
          </th>
          <th>
              Содержание
          </th>
      </thead>
      <tr>
          <td>
              {{ post.post_name }}
          </td>
          <td>
              {{ post.post_date | date:'d M Y' }}
          </td>
          <td>
              {{ post.content }}
          </td>
      </tr>
  </table>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="удалить">
    </form>
{% endblock content %}

Newspaper/templates/posts.html
<!--  наследуемся от шаблона default.html, который мы создавали ещё во времена flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

<!-- Название у нас будет products -->
{% block title %}
    Новости
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
    <h1>Все новости</h1>
    <h3>Общее количество: {{ posts | length }}</h3>
    <hr>
    {% if posts %} <!-- Выводим товары только если они есть с помощью тега if -->
        <table>
            <tr>
                <td>
                    Название
                </td>
                <td>
                    Дата публикации
                </td>
                <td>
                    Содержание
                </td>
            </tr>
        {% for post in page_obj %} <!-- Для каждого товара будете генерироваться новая строчка,
            т.е. новый html код. При этом сам цикл работет точно также, как и в python.
            product — переменная цикла, т.е. наш товар взятый из общего списка -->
            <tr>
                <td>
                    <a href="{% url 'news:post' post.id %}">{{ post.post_name | censor:'new' }}</a> <!-- не забываем что переменные в шаблоне ничем не отличаются
                        от переменных в python. Здесь также можно получать доступ к полям класса.
                        Например здесь мы выводим имя, в следующем столбце описание, и т.д.  -->
                    <a href="{% url 'news:post_update' post.id %}"><u>Редактировать</u></a>
                <!-- добавим ссылку на редактирование товара-->
                 <a href="{% url 'news:post_delete' post.id %}"><u> Удалить </u></a>
                <!-- добавим ссылку на удаление товара-->
                </td>
                <td>
                    {{ post.post_date | date:'d M Y' }}
                </td>
                <td>
                    {{ post.content | truncatechars:50 | censor:'ipsum' }}
                </td>
            </tr>
        {% endfor %}
        </table>
        <hr>
        <a href="{% url 'news:post_create' %}">Добавить новую запись</a> <br>
        <!-- Проверяем что поддерживается постраничный вывод -->
        <hr>
        {% if is_paginated %}

        <!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
            {% if page_obj.has_previous %}
                <a href="?page=1">First</a>
                <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
            {% endif %}

        <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a>{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

        <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">>>></a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}

<!--        <form method="POST">-->
<!--            {% csrf_token %}-->
<!--            {{ form }} &lt;!&ndash; Теперь нам нужна только готовая форма и кнопка &ndash;&gt;-->
<!--            <input type="submit" value="Добавить запись">-->
<!--        </form>-->
    {% else %} <!-- Если товаров нет, то говорим что товаров нет ;) -->
        <h2>Новостей нет!</h2>
        <a href="{% url 'news:post_create' %}">Добавить новую запись</a> <br>
    {% endif %}

{% endblock content %}

Newspaper/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

<!-- Название у нас будет products -->
{% block title %}
    Search
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
    <h1>Поиск новостей</h1>
    <h3>Общее количество: {{ posts | length }}</h3>
    <hr>
    <form method="GET">
        {{ filter.form }} <!-- Форму от фильтров за нас сделает django. А вот кнопку, увы
                            придётся делать самому -->
        <input type="submit" value="Найти">
    </form>
    {% if posts %} <!-- Выводим товары только если они есть с помощью тега if -->
        <table>
            <tr>
                <td>
                    Название
                </td>
                <td>
                    Дата публикации
                </td>
                <td>
                    Содержание
                </td>
            </tr>
        {% for post in filter.qs %} <!-- Для каждого товара будете генерироваться новая строчка,
            т.е. новый html код. При этом сам цикл работет точно также, как и в python.
            product — переменная цикла, т.е. наш товар взятый из общего списка -->
            <tr>
                <td>
                    {{ post.post_name | censor:'new' }} <!-- не забываем что переменные в шаблоне ничем не отличаются
                        от переменных в python. Здесь также можно получать доступ к полям класса.
                        Например здесь мы выводим имя, в следующем столбце описание, и т.д.  -->
                </td>
                <td>
                    {{ post.post_date | date:'d M Y' }}
                </td>
                <td>
                    {{ post.content | truncatechars:50 | censor:'ipsum' }}
                </td>
            </tr>
        {% endfor %}
        </table>
        {% if is_paginated %}

        <!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
            {% if page_obj.has_previous %}
                <a href="?page=1">First</a>
                <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
            {% endif %}

        <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a>{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

        <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">>>></a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    {% else %} <!-- Если товаров нет, то говорим что товаров нет ;) -->
        <h2>Новостей не найдено!</h2>
    {% endif %}

{% endblock content %}